### PR TITLE
Fix stack trace check for “multiple promises”

### PR DESCRIPTION
**Pull request by addaleax**
`getFileName()` returns `null` for calls from internal methods (like the Promise constructor itself).

Fixes: https://github.com/stevekane/promise-it-wont-hurt/issues/122

### CODE REVIEW

**Comment by TimothyGu** [comment]
@addaleax Would you be interested in helping maintain this tutorial? I haven't been exactly a good steward of this module, but it is still a good intro to promises (except the many outstanding issues).

**Comment by addaleax** [comment]
@TimothyGu Sorry, that comment kind of went under min my notifications. I mean, I can’t guarantee anything but if you add me as a co-maintainer I’ll do the best I can :)

**Comment by TimothyGu** [comment]
Merged, unfortunately I don't have the credentials to add you, so @stevekane would you mind adding @addaleax as a collaborator in this repo?

**Comment by stevekane** [comment]
Done. Thanks for helping out.

**Comment by addaleax** [comment]
Sure! @TimothyGu or @stevekane can you do an npm release with the merged commit? is there anything I can do to help with that?

**Comment by TimothyGu** [comment]
@addaleax I've added you as an npm owner :100:

**Pull request merged**
