### PR TITLE
L10n FR now up-to-date

### PR DESCRIPTION
**Pull request by tdd**
Hey @TimothyGu and team!

So, as promised, even if in the nick of time, here's the full up-to-date FR L10n for the workshopper! Still, a couple noteworthy items:

* `workshopper-timer` has no provisions for i18n, which means it's the one displayed message that is fixed-language. It would be great if it could rely on `workshopper`'s general `i18n/<lang>.json` system to localize its message.
* The verifier for the "shortcuts" exercise doesn't properly detect `catch` usage (at least on my 4.2.6 through nvm on OSX)
* A number of exercises were still Q-based when they didn't need to (the q-io ones are fine, but other, intermediary ones were still using Q in their solutions), so I moved that over to ES2015 promises, **but…** their `exercise.js` doesn't use the wrap/exercise harness that inspects internal use of methods and, more importantly, sneaks in `es6-promise` if needed.

So!  I'd **love** for this to be merged in and a new release published. I don't mind that being, say, 2.0.0-pre, npm dist-tag'd as `next`, if you're uncomfortable releasing that as-is as `latest`. But it would be great if we could install it straightforwardly through npm on Tuesday, for my Node workshop. Otherwise I'll just have them install through Git branch ref.

Cheers!

### CODE REVIEW

**Comment by TimothyGu** [comment]
> The verifier for the "shortcuts" exercise doesn't properly detect `catch` usage (at least on my 4.2.6 through nvm on OSX)

That should have been fixed in 7b2dcac6b25e304098a91e583cfbce1be9a878ac…

**Comment by TimothyGu** [comment]
The English (and code) portion looks good. I also started working on converting throw-an-error to ES2015, but I'm happy to publish this as 1.0.0-alpha.1 right now even when I haven't gotten through all of them

**Comment by TimothyGu** [comment]
> `workshopper-timer` has no provisions for i18n, which means it's the one displayed message that is fixed-language. It would be great if it could rely on `workshopper`'s general `i18n/<lang>.json` system to localize its message.

This is fairly difficult since the workshopper-exercise framework doesn't allow adding more JSON stores, which means that to add i18n to workshopper-timer there are only two ways:

- use a callback to allow the workshopper writer to use their own `this.__`
- manually use i18n-core etc.

I'm leaning towards the second option.

**Comment by tdd** [comment]
Hey Tim!

:+1: on 1.0.0-alpha. As for i18n of `workshopper-timer`: it's perhaps easiest to just go as `workshopper-exercise` does, and have its own `i18n` dir in there, for translators to contribute to.

**Comment by TimothyGu** [comment]
Yeah.

**Comment by tdd** [comment]
Might I bother you then to release 1.0.0-alpha as next today? This way I can have them install it easily tomorrow :wink:

**Comment by TimothyGu** [comment]
Okay I'll try to do it now.

**Comment by TimothyGu** [comment]
1.0.0-alpha.1 is published as `latest` now. 0.2.5 remains the `stable` version.

**Comment by tdd** [comment]
Hey there!

Didn't know you could mark a -alpha as latest. Seems there's some
propagation issue right now, as I see stable but don't see latest as 1.1.0-
alpha yet. Will check later today.

Thanks!


On Mon, Feb 1, 2016, at 16:59, Timothy Gu wrote:
> 1..0-alpha.1 is published as latest now. 0.2.5 remains the stable
>   version.


> — Reply to this email directly or view it on GitHub[1].


>

--
Christophe Porteneuve
tdd@tddsworld.com
 


Links:

  1. https://github.com/stevekane/promise-it-wont-hurt/pull/65#issuecomment-178041907

**Pull request merged**
